insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (1, '10/17/2023', 'Purolator', 7, 15, 14);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (2, '01/07/2024', 'UPS', 6, 9, 3);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (3, '02/10/2024', 'Fedex', 8, 12, 10);
insert into public."orderInvoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (4, '06/13/2023', 'Fedex', 7, 12, 8);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (5, '05/05/2023', 'UPS', 3, 12, 5);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (6, '09/19/2023', 'Fedex', 3, 14, 9);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (7, '10/31/2023', 'Fedex', 4, 13, 6);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (8, '08/06/2023', 'Canada Post', 1, 14, 5);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (9, '04/08/2023', 'Canada Post', 2, 11, 12);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (10, '11/22/2023', 'Canada Post', 6, 14, 11);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (11, '07/30/2023', 'Purolator', 2, 9, 7);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (12, '06/28/2023', 'Fedex', 1, 10, 2);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (13, '02/05/2024', 'Fedex', 3, 13, 13);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (14, '07/31/2023', 'Canada Post', 1, 13, 1);
insert into public."order_invoice" (invoice_ID, date, shipping_information, customer_ID, vendor_ID, product_ID) values (15, '11/16/2023', 'Purolator', 5, 11, 4);
