insert into public."product_order" (product_ID, invoice_ID) values (1, 14);
insert into public."product_order" (product_ID, invoice_ID) values (2,12);
insert into public."product_order" (product_ID, invoice_ID) values (3, 2);
insert into public."product_order" (product_ID, invoice_ID) values (4, 15);
insert into public."product_order" (product_ID, invoice_ID) values (5, 5);
insert into public."product_order" (product_ID, invoice_ID) values (6, 7);
insert into public."product_order" (product_ID, invoice_ID) values (7, 11);
insert into public."product_order" (product_ID, invoice_ID) values (8, 4);
insert into public."product_order" (product_ID, invoice_ID) values (9, 6);
insert into public."product_order" (product_ID, invoice_ID) values (10, 3);
insert into public."product_order" (product_ID, invoice_ID) values (11, 10);
insert into public."product_order" (product_ID, invoice_ID) values (12, 9);
insert into public."product_order" (product_ID, invoice_ID) values (13, 13);
insert into public."product_order" (product_ID, invoice_ID) values (14, 1);
insert into public."product_order" (product_ID, invoice_ID) values (15, 8);
